config/routes.rb
Toourhouse::Application.routes.draw do
  
  resources :vsignups
  resources :osignups
  resources :events
  resources :responsibilities
  resources :organizations

  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'organizations' => 'organizations#index'
  get 'responsibilities' => 'events#index'

  get "users/show"
  devise_for :users
  match 'users/:id' => 'users#show', as: :user
  get 'users' => 'users#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	# Accessible attributes
  attr_accessible :end_date, :name, :start_date

  # Validations
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  # Relationships
  has_many :Osignups, :dependent => :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  # Load cancan authorization resources
  load_and_authorize_resource
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="row-fluid">
  <div class="span12">
    <h2><%= event.name %></h2>
    <h4>From <%= event.start_date.strftime("%a, %b %d") %> to <%= event.end_date.strftime("%a, %b %d") %></h4>
  	<% if can? :create, @osignups %>
			<p>
				<%= link_to 'Sign my organization up for this event!', new_osignup_path %>
			</p>
		<% end %>
  	<p>
  		<%= link_to 'Show', event_path(event) %>
  		<% if can? :update, event %>
  			<%= link_to 'Edit', edit_event_path(event) %>
  		<% end %>
  		<% if can? :destroy, event %>
  			<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
  		<% end %>
  	</p>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<%= render @events %>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @event.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @event.end_date %>
</p>

<% if can? :create, @osignups %>
	<p>
		<%= link_to 'Sign my organization up for this event!', new_osignup_path %>
	</p>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>