config/routes.rb
Toourhouse::Application.routes.draw do
  
  resources :vsignups
  resources :osignups
  resources :events
  resources :responsibilities
  resources :organizations

  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'organizations' => 'organizations#index'
  get 'responsibilities' => 'events#index'

  get "users/show"
  devise_for :users
  match 'users/:id' => 'users#show', as: :user
  get 'users' => 'users#index'

end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  # Accessible properties
  attr_accessible :description, :name, :organization_type, :positions

  # Validates
  validates :name, presence: true
  validates :description, presence: true
  validates :organization_type, presence: true
  validates :positions, numericality: true

  # Relationships
<<<<<<< HEAD
  has_many :Vsignups, :dependent => :destroy
=======
  has_many :vsignups, :dependent => :destroy
>>>>>>> 19f3ae6cc4629fcb48706e99ff19aeadf87f57b8
end

app/controllers/responsibilities_controller.rb
class ResponsibilitiesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # Load cancan authorization resources
  load_and_authorize_resource
  # GET /responsibilities
  # GET /responsibilities.json
  def index
    @responsibilities = Responsibility.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responsibilities }
    end
  end

  # GET /responsibilities/1
  # GET /responsibilities/1.json
  def show
    @responsibility = Responsibility.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @responsibility }
    end
  end

  # GET /responsibilities/new
  # GET /responsibilities/new.json
  def new
    @responsibility = Responsibility.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @responsibility }
    end
  end

  # GET /responsibilities/1/edit
  def edit
    @responsibility = Responsibility.find(params[:id])
  end

  # POST /responsibilities
  # POST /responsibilities.json
  def create
    @responsibility = Responsibility.new(params[:responsibility])

    respond_to do |format|
      if @responsibility.save
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully created.' }
        format.json { render json: @responsibility, status: :created, location: @responsibility }
      else
        format.html { render action: "new" }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responsibilities/1
  # PUT /responsibilities/1.json
  def update
    @responsibility = Responsibility.find(params[:id])

    respond_to do |format|
      if @responsibility.update_attributes(params[:responsibility])
        format.html { redirect_to @responsibility, notice: 'Responsibility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @responsibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibilities/1
  # DELETE /responsibilities/1.json
  def destroy
    @responsibility = Responsibility.find(params[:id])
    @responsibility.destroy

    respond_to do |format|
      format.html { redirect_to responsibilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/responsibilities_helper.rb
module ResponsibilitiesHelper
end

app/views/responsibilities/_form.html.erb
<%= simple_form_for(@responsibility, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :organization_type, collection: ["Host Organization", "Support Organization", "TOH Staff", "Transportation"] %>
    <%= f.input :positions, hint: "Enter the number of volunteers needed per night for this role", input_html: { value: '1'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/responsibilities/_responsibility.html.erb
<div class="box">
  <h6><%= responsibility.organization_type %>:</h6>
  <h3><%= responsibility.name %></h3>
  <p class="description">
			<%= responsibility.description %>
  </p>

  <p>
	  <%= link_to 'Show', responsibility %>
	  <%= link_to 'Edit', edit_responsibility_path(responsibility) %>
	  <%= link_to 'Destroy', responsibility, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/responsibilities/edit.html.erb
<h1>Editing responsibility</h1>

<%= render 'form' %>

<%= link_to 'Show', @responsibility %> |
<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/index.html.erb
<h1>Volunteer Opportunities</h1>

<div id="responsibilities">
  <%= render @responsibilities %>
</div>

<br />

<%= link_to 'New Responsibility', new_responsibility_path %>

app/views/responsibilities/new.html.erb
<h1>New responsibility</h1>

<%= render 'form' %>

<%= link_to 'Back', responsibilities_path %>

app/views/responsibilities/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <h3><%= @responsibility.name %></h3>
      <h6><%= @responsibility.organization_type %></h6>
      <p class="description">
        <blockquote><%= @responsibility.description %></blockquote>
      </p>
      <p>
        For each night, there
        <% if(@responsibility.positions > 1) %>
        	are
      	<% else %>
      		is
    		<% end %>
				<%= @responsibility.positions %>
				<%= @responsibility.name %>
				needed.
      </p>
      <%= link_to 'Edit', edit_responsibility_path(@responsibility) %> |
			<%= link_to 'Back', responsibilities_path %>
    </div>
  </div>
</div>