config/routes.rb
Toourhouse::Application.routes.draw do
  
  resources :vsignups
  resources :osignups
  resources :events
  resources :responsibilities
  resources :organizations

  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'organizations' => 'organizations#index'
  get 'responsibilities' => 'events#index'

  get "users/show"
  devise_for :users
  match 'users/:id' => 'users#show', as: :user
  get 'users' => 'users#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	# Accessible attributes
  attr_accessible :city, :country, :description, :name, :state, :street, :website, :zipcode, :image

  # Validations
  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, numericality: true, presence: true
  validates :country, presence: true
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                               size: { less_than: 5.megabytes} 

  # Relationships
  has_attached_file :image, styles: {tiny: "25x25>", small: "50x50>", profile: "180x180>"}, :dependent => :destroy
<<<<<<< HEAD
  has_many :Users
  has_many :Osignups, :dependent => :destroy
=======
  has_many :users
  has_many :osignups, :dependent => :destroy
>>>>>>> 19f3ae6cc4629fcb48706e99ff19aeadf87f57b8
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # Load cancan authorization resources
  load_and_authorize_resource
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state, input_html: { maxlength: 2, value: 'VA'}  %>
    <%= f.input :zipcode, input_html: { maxlength: 5 } %>
    <%= f.input :country, priority: ["United States"] %>
    <%= f.input :website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<tr>
    <td><%= image_tag organization.image(:small) %></td>
    <td><%= organization.name %></td>
    <td><%= organization.street %></td>
    <td><%= organization.city %></td>
    <td><%= organization.zipcode %></td>
    <td><%= organization.state %></td>
    <td><%= organization.country %></td>
    <td><%= link_to organization.website %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Our Organizations</h1>

<table class="table table-striped">
  <thead>
    <th>Image</th>
    <th>Name</th>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

  <tbody>
    <%= render @organizations %>
  </tbody>

</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <h3><%= @organization.name %></h3>
      <%= image_tag @organization.image %>
      <p class="description">
        <blockquote><%= @organization.description %></blockquote>
      </p>
      <p>
        <b>Address:</b><br />
        <%= @organization.street %><br />
        <%= @organization.city %>, <%= @organization.state %> <%= @organization.zipcode %><br />
        <%= @organization.country %>
      </p>
      <p>
        <b>Website:</b><br />
        <%= link_to @organization.website %>
      </p>
      <%= link_to 'Edit', edit_organization_path(@organization) %> |
      <%= link_to 'Back', organizations_path %>
    </div>
  </div>
</div>