config/routes.rb
Toourhouse::Application.routes.draw do
  
  resources :vsignups
  resources :osignups
  resources :events
  resources :responsibilities
  resources :organizations

  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'organizations' => 'organizations#index'
  get 'responsibilities' => 'events#index'

  get "users/show"
  devise_for :users
  match 'users/:id' => 'users#show', as: :user
  get 'users' => 'users#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "To Our House", "http://toourhouse.org" %>
    by <%= link_to "Ben Han and Luke Zimmerman", "http://pamplin.vt.edu" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <%= link_to "To Our House", root_path, class: "brand" %>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                        <li>    
                            <%= link_to "Organizations",  organizations_path %>
                        </li>
                        <li>    
                            <%= link_to "Events",  events_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                      <% if user_signed_in? %>
                        <li><%= link_to "Volunteer +", "#" %></li>
                        <li id="profpic">
                          <%= link_to(current_user) do %>
                            <%= image_tag current_user.image(:tiny) %>
                            <%= current_user.name %>
                          <% end %>
                        </li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                         <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Our House</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>